'use client';

import React, { useState } from 'react';
import { catalog, workloads } from './catalog.js';
import { defaults, evaluate, validateStep } from './engine.js';
import { getFleetGuidance } from './fleetGuidance.js';
import FleetStep, { FleetNotices } from './FleetStep.jsx';
const steps = ['Workload & platform', 'Fleet, fabric & storage', 'Facility & power'];
const number = n => n === null ? 'Unconfirmed' : n.toLocaleString('en-US');
export default function InfrastructureAdvisor() {
 const [input,setInput]=useState({...defaults});
 const [step,setStep]=useState(0);
 const [completed,setCompleted]=useState(false);
 const [errors,setErrors]=useState([]);
 const result=evaluate(input), guidance=getFleetGuidance(input);
 const selected=catalog.platforms.find(p=>p.id===input.gpuModel);
 const change=(key,value)=>{setCompleted(false);setErrors([]);setInput(old=>({...old,[key]:value,...(key==='vendor'?{gpuModel:'Any',unitKw:'',serverU:''}:key==='gpuModel'?{unitKw:'',serverU:''}:{})}));};
 const navigate=next=>{
  const issues=next>step ? Array.from({length:next},(_,i)=>validateStep(input,i)).flat() : [];
  setErrors(issues); if(!issues.length){setCompleted(false);setStep(next);}
 };
 const field=(key,label,placeholder,unit)=><label className="field">{label}<div className="input-wrap"><input type="number" min="0" step={['gpuCount','maxRacks','serverU'].includes(key)?'1':'any'} value={input[key]} placeholder={placeholder} onChange={e=>change(key,e.target.value)}/><span>{unit}</span></div></label>;
 const download=()=>{
  const blob=new Blob([JSON.stringify({generatedAt:new Date().toISOString(),catalogVersion:catalog.version,source:catalog.source,qualification:catalog.qualification,assumptions:catalog.assumptions,inputs:input,...result},null,2)],{type:'application/json'});
  const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='atlas-sizing-summary.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 };
 return <div className="shell"><aside className="sidebar"><a className="brand" href="./"><span className="brand-icon">A</span>atlas.</a><div className="workspace">SALES WORKSPACE</div><div className="nav-active">Infrastructure advisor</div><div className="sidebar-note">Discovery workspace<p>From customer ambition<br/>to a clearer infrastructure plan.</p></div></aside>
 <main><header><div>Workspace / Infrastructure advisor</div><span className="pill">Planning mode</span></header><section className="intro"><div className="eyebrow">AI INFRASTRUCTURE · GUIDED DISCOVERY</div><h1>Build the right foundation.</h1><p>Use the sales table to qualify platforms, plan the fleet and review facility readiness.</p></section>
 <div className="content"><section className="discovery panel"><div className="panel-heading"><div><span className="eyebrow">CUSTOMER REQUIREMENTS</span><h2>Let’s size the opportunity</h2></div><button className="text-button" onClick={()=>{setInput({...defaults});setStep(0);setCompleted(false);setErrors([]);}}>Reset</button></div>
 <div className="stepper">{steps.map((s,i)=><button key={s} className={step===i?'step active':'step'} onClick={()=>navigate(i)} aria-current={step===i?'step':undefined}><span>{i+1}</span><small>{s}</small></button>)}</div>
 <div className="form-body"><span className="eyebrow">STEP 0{step+1} OF 03</span><h2>{steps[step]}</h2>
 {step===0 && <><fieldset><legend>GPU vendor preference</legend><div className="choices">{['NVIDIA','AMD','Any'].map(v=><button key={v} aria-pressed={input.vendor===v} className={input.vendor===v?'choice selected':'choice'} onClick={()=>change('vendor',v)}>{v==='Any'?'No preference':v}</button>)}</div></fieldset>
 <label className="field">Platform<select value={input.gpuModel} onChange={e=>change('gpuModel',e.target.value)}><option value="Any">All platforms</option>{catalog.platforms.filter(p=>input.vendor==='Any'||p.vendor===input.vendor).map(p=><option key={p.id} value={p.id}>{p.name}{p.status==='roadmap'?' — roadmap':''}</option>)}</select></label>
 <fieldset><legend>Primary workload</legend><div className="workloads">{Object.entries(workloads).map(([id,label])=><button key={id} aria-pressed={input.workload===id} className={input.workload===id?'workload selected':'workload'} onClick={()=>change('workload',id)}><strong>{label}</strong></button>)}</div></fieldset>
 <FleetNotices guidance={guidance}/>{selected && <div className="hint"><strong>{selected.name}</strong><p>{selected.memory}</p><p>{selected.configuration}</p><p>{selected.considerations}</p></div>}<p className="muted">Platform eligibility follows the use cases listed in the supplied table. Recommendations still require workload validation.</p></>}
 {step===1 && <FleetStep input={input} change={change} field={field} guidance={guidance}/>}
 {step===2 && <><label className="field">Available cooling<select value={input.cooling} onChange={e=>change('cooling',e.target.value)}><option value="unknown">Not yet confirmed</option><option value="air">Air only</option><option value="liquid">Direct liquid cooling available</option></select></label>
 {field('maxMw','Maximum facility power budget','Optional','MW')}{field('rackKw','Maximum compute rack power','Optional','kW / rack')}{field('maxRacks','Maximum compute racks','Optional','racks')}
 {selected && selected.status!=='roadmap' ? <><p className="muted">Enter confirmed OEM specifications for {selected.name}. Blank power uses the table’s server or rack rating where available. GPU-only ratings cannot establish full-server demand.</p>{field('unitKw',`OEM full-${selected.unitType} peak power`,selected.power.unitKw ? `Reference: ${selected.power.unitKw}` : 'Unconfirmed',`kW / ${selected.unitType}`)}{selected.unitType==='server' && field('serverU','OEM server height','Unconfirmed','U')}</> : <p className="muted">Select one confirmed platform in step 1 to enter its OEM power and chassis specifications.</p>}
 <div className="hint">{catalog.assumptions.note}</div></>}
 {errors.length>0 && <div className="empty" role="alert"><h3>Check your inputs</h3>{errors.map(e=><p key={e}>{e}</p>)}</div>}
 </div><div className="form-footer"><span>{completed?'Discovery complete':'Results after step 3'}</span><div>{step>0 && <button className="secondary" onClick={()=>navigate(step-1)}>Back</button>}{step<2?<button className="primary" onClick={()=>navigate(step+1)}>Continue →</button>:completed?<button className="primary" onClick={download}>Export plan ↓</button>:<button className="primary" onClick={()=>{setErrors(result.errors);setCompleted(!result.errors.length);}}>Show configurations →</button>}</div></div></section>
 {!completed ? <section className="results panel results-placeholder"><span className="eyebrow">YOUR INFRASTRUCTURE PLAN</span><h2>Complete discovery to see your plan</h2><p>Review all three steps to see platform candidates, storage recommendations and outstanding engineering checks.</p></section> : <section className="results"><div className="results-header"><div><span className="eyebrow">YOUR INFRASTRUCTURE PLAN</span><h2>Power-sized configurations <span className="count">{result.matches.length}</span></h2></div></div><p className="muted">Configurations include full-unit power and facility overhead. Reference ratings remain provisional. Enter a facility budget in step 3 to check available capacity.</p>
 {result.matches.length===0 && <div className="empty"><h3>No power-sized configuration</h3><p>No configuration can currently be sized within the supplied constraints. Review missing power specifications and exclusions below.</p></div>}
 {result.matches.map(r=><article key={r.platform.id} className="recommendation panel"><div className="card-top"><span className="eyebrow">{r.platform.vendor}</span><span className="tag">Engineering review</span></div><h2>{r.platform.name}</h2><p className="sku">{r.platform.memory}</p><div className="metrics"><div><strong>{number(r.provisionedGpus)}</strong><small>Provisioned GPUs</small></div><div><strong>{number(r.units)}</strong><small>{r.platform.unitType==='rack'?'Scale-up racks':'Servers'}</small></div><div><strong>{number(r.racks)}</strong><small>Compute racks</small></div><div><strong>{r.facilityMw===null?'Unconfirmed':r.facilityMw.toFixed(2)}</strong><small>Facility peak MW</small></div></div><div className="justification"><p>{r.extraGpus} GPUs above target after rounding to whole {r.platform.unitType}s.</p><strong>Power calculation</strong><p>{r.units} {r.platform.unitType}s × {r.unitKw} kW = {r.computeMw.toFixed(3)} MW compute. With {catalog.assumptions.ancillaryFraction * 100}% additional IT power and PUE {catalog.assumptions.pue}, facility demand is {r.facilityMw.toFixed(3)} MW.</p><p>{r.powerHeadroomMw === null ? 'Facility budget not supplied — available power has not been checked.' : `Within ${r.powerBudgetMw} MW facility budget · ${r.powerHeadroomMw.toFixed(3)} MW remaining.`}</p><p>{r.rackPeakKw === null ? 'Rack power and packing need OEM height and rack capacity.' : `Maximum compute rack draw: ${r.rackPeakKw.toFixed(1)} kW${input.rackKw ? ` / ${input.rackKw} kW limit` : ' (rack capacity not supplied)'}.`}</p><strong>Power consumption / rating</strong><p>{r.platform.power.description}</p><p>Calculation basis: {r.powerBasis === 'oem-input' ? 'Entered OEM full-unit power' : r.powerBasis === 'rack-reference' ? 'Workbook rack rating (provisional)' : r.powerBasis === 'server-reference' ? 'Workbook server rating (provisional)' : 'Full-unit power unconfirmed'}{r.unitKw !== null ? ` · ${r.unitKw} kW per ${r.platform.unitType}` : ''}</p>{r.gpuOnlyMw !== null && <p>GPU-only fleet rating: {r.gpuOnlyMw.toFixed(3)} MW. Excludes host and facility overhead.</p>}<strong>Network</strong><p>{r.platform.network}</p><strong>Platform storage shortlist</strong><p>{r.platform.storage}</p><strong>Considerations</strong><p>{r.platform.considerations}</p></div><details><summary>Outstanding checks and source</summary><ul>{r.reviews.map(x=><li key={x}>{x}</li>)}</ul><p>{r.platform.source.file} · {r.platform.source.sheet}!{r.platform.source.range}</p></details></article>)}
 {result.incomplete.length>0 && <section className="recommendation panel"><h2>Needs power specifications ({result.incomplete.length})</h2><p>These platforms are not included in the final configurations because their power or supplied facility limits cannot yet be checked.</p>{result.incomplete.map(r=><div className="hint fleet-guidance" key={r.platform.id}><strong>{r.platform.name}</strong><p>{r.platform.power.description}</p>{r.gpuOnlyMw!==null && <p>GPU-only fleet rating: {r.gpuOnlyMw.toFixed(3)} MW. Full-server and facility demand remain unconfirmed.</p>}<ul>{r.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><button className="secondary" onClick={()=>{change('gpuModel',r.platform.id);setStep(2);}}>Enter specifications</button></div>)}</section>}
 {result.pending.map(r=><article className="recommendation panel" key={r.platform.id}><span className="tag">Roadmap — sizing unavailable</span><h2>{r.platform.name}</h2><p>{r.platform.considerations}</p><p>{r.platform.power.description}</p>{r.reasons.map(x=><p key={x}>{x}</p>)}</article>)}
 {result.storage && <article className="recommendation panel"><h2>Storage for {workloads[input.workload]}</h2><p>{result.storage.vendors}</p><p>{result.storage.reason}</p><p>{result.storage.considerations}</p></article>}
 {result.rejected.length>0 && <details className="rejections"><summary>Excluded platforms ({result.rejected.length})</summary>{result.rejected.map(r=><div key={r.platform.id}><strong>{r.platform.name}</strong><ul>{r.reasons.map(x=><li key={x}>{x}</li>)}</ul></div>)}</details>}
 <p className="footnote">Source: {catalog.source} · {catalog.version}<br/>{catalog.qualification}<br/>{catalog.assumptions.note}</p></section>}
 </div><footer>ATLAS / SOLUTIONS ADVISORY <span>Discovery → Configuration → Conversation</span></footer></main></div>;
}
